import Footer from "@/components/footer/Footer"
import Navbar from "@/components/navbar/Navbar"
import "@/Styles/globals.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
	  <html lang="en">
		<head>
		</head>
		<body>
			<Navbar/>
			{children}
			<Footer/>
		</body>
    </html>
  )
}
