version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - /var/lib/postgresql/data:/Users/mouaammo/goinfre/PgData
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ft_transcendence
      POSTGRES_USER: mouad
      POSTGRES_PASSWORD: mouad
    restart: on-failure

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: on-failure

  frontend:
    build: frontend
    hostname: frontend
    container_name: frontend
    restart: on-failure

  backend:
    build: backend
    hostname: backend
    container_name: backend
    depends_on:
      - postgres
      - redis
    restart: on-failure
    environment:
      - DATABASE_URL=postgres://mouad:mouad@postgres:5432/your_database_name
      - REDIS_URL=redis://redis:6379
      - DJANGO_SETTINGS_MODULE=core.settings
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin123
    env_file:
      - .env

  nginx:
    build: services/nginx
    hostname: nginx
    ports:
      - "443:443"
    depends_on:
      - backend
      - frontend

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: /Users/mouaammo/goinfre/PgData
      o: bind