version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ft_transcendence
      POSTGRES_USER: mouad
      POSTGRES_PASSWORD: mouad
    restart: on-failure

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: on-failure

  frontend:
    build:
      context: ./frontend
    hostname: frontend
    container_name: frontend
    ports:
      - "3000:3000"
    restart: on-failure

  backend:
      build:
        context: ./backend
      depends_on:
        - postgres
        - redis
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - REDIS_URL=redis://redis:6379/0
        - DATABASE_URL=postgres://mouad:mouad@postgres:5432/ft_transcendence
        - REDIS_URL=redis://redis:6379
        - DJANGO_SETTINGS_MODULE=core.settings
      ports:
        - "8000:8000"
      restart: on-failure
      env_file:
        - .env

  nginx:
    build:
      context: ./services/nginx
    hostname: nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - backend
      - frontend

volumes:
  postgres-data:
