version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ft_transcendence
      POSTGRES_USER: mouad
      POSTGRES_PASSWORD: mouad
    restart: on-failure
    networks:
      - ft_transcendence

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: on-failure
    networks:
      - ft_transcendence

  frontend:
    build:
      context: ./frontend
    hostname: frontend
    container_name: frontend
    ports:
      - "3000:3000"
    restart: on-failure
    networks:
      - ft_transcendence

  backend:
    build:
      context: ./backend
    hostname: backend
    container_name: backend
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://mouad:mouad@postgres:5432/ft_transcendence
      - REDIS_URL=redis://redis:6379
      - DJANGO_SETTINGS_MODULE=core.settings
    ports:
      - "8000:8000"
    restart: on-failure
    env_file:
      - .env
    networks:
      - ft_transcendence

  nginx:
    build:
      context: ./services/nginx
    hostname: nginx
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - backend
      - frontend
    networks:
      - ft_transcendence

volumes:
  postgres-data:

networks:
  ft_transcendence:
    driver: bridge